export type MarginNote = {
  paragraph: number;
  label: string;
  body: string;
  kind?: "creative" | "technical" | "edit";
};

export type Chapter = {
  id: string;
  number: number;
  title: string;
  minutes: number;
  status?: "Drafting" | "Editing" | "Published";
  paragraphs: string[];
  notes?: MarginNote[];
};

// Sourced from The_Spectator_Rewritten_1-2.docx (Andre Reston).
// Full manuscript for chapters 1–10 + opening of Ch. 11.
// Chapters 12–23 are stubs pending upload. Ch. 24 is the live drafting room.
export const chapters: Chapter[] = [
  {
    id: "ch-01", number: 1, title: "The Return", minutes: 9, status: "Editing",
    paragraphs: [
      "Purple-red flames consumed the battlefield. The air was thick with ash and the smell of burning flesh. Bodies in silver armor lay scattered across the ground, fingers still locked around swords they would never use again. A triangular banner had caught fire atop its broken pole, and the castle walls had given way into heaps of rubble and ruin.",
      "He alone remained to witness it.",
      "Cyrus knelt in the middle of the destruction and could not make himself move. Despair had reached into every part of him. His eyes would not leave the flames. It was as though his soul had already left and his body simply had not caught up yet.",
      "Part of him kept insisting this was a nightmare. That he would wake beneath a familiar ceiling, in a familiar bed, and none of it would have happened. But the heat on his face was real. The smell was real. The silence between the crackling of the fire was real.",
      "A man descended from the air above the ruined field. He wore a dark violet robe, its lower hem tattered and swaying in the heated wind. His hood was drawn, and a black mask covered the lower half of his face — painted across it, a silver grin stretched unnaturally wide. His skin, where it showed, was pale as something long dead. He moved as though gravity was a formality he had decided to humor, and when he reached the ground, he stopped directly in front of Cyrus.",
      "“Wonderful sight, isn't it?”",
      "Cyrus said nothing. He stared ahead as though the man were not there.",
      "“An abomination of existence, reduced to ashes,” the robed man continued, extending one arm as if presenting his work. “The foolish creations of humanity, erased at last. Someone was always going to do this eventually.” He paused. “The only way to end the chaos was to destroy everything.”",
      "Still, Cyrus did not speak. The man lowered his hood. Dark blue hair fell to his neck. His eyes were crimson, faintly luminous against the firelight.",
      "“You may call me a madman,” he said calmly. “But I have never been wrong.”",
      "At last, Cyrus lifted his head. Tears threatened at the corners of his eyes, but what burned in them was not grief alone. It was rage, and something beneath rage that had no clean name. “I wouldn't call you a madman. You're worse than that. You're a psychopath pretending to be a god.”",
      "“You're delusional if you think you can kill me. Not even the whole world could leave a scratch on my body.”",
      "“Then I'll do what the world couldn't.” Cyrus seized his sword and lunged.",
      "The robed man exhaled. An invisible force hurled Cyrus into the air. Before he could recover, the man raised one hand and froze him in place — effortlessly, the way a man might pin a moth to a board. Then the robed man snapped his fingers. Blue flames engulfed Cyrus entirely.",
      "His scream tore across the empty battlefield. When the fire died, he dropped to the ground. His body was covered in burns. He gritted his teeth, forced himself to reach inward for whatever healing was left in him, and pushed himself forward again.",
      "The robed man pointed one finger toward the sky. Lightning answered. A bolt struck Cyrus directly, convulsing through every muscle, filling the air again with the smell of burned flesh.",
      "He charged again anyway. He swung his sword in a diagonal arc and released a wind slash toward the robed man. The man raised one hand; a barrier absorbed the impact without visible strain. For one instant, it seemed possible.",
      "Then the world stopped. Everything held perfectly still. Cyrus felt it before he understood it — a wrongness, a suspension. His eyes widened. Hundreds of black crystalline spikes materialized in the air around him.",
      "*There is no way I can survive this.*",
      "They drove forward simultaneously. One after another, they punched through his flesh and pinned him against the steel wall behind him. Blood filled the air. The pain arrived in a wave so total that it left no room for thought, and no room for sound — he could not even scream.",
      "Footsteps moved toward him through the silence. They stopped. “I told you,” the robed man said quietly. “You cannot defeat me.” The man sighed and pressed his palm against Cyrus's forehead.",
      "“Just kill me already,” Cyrus whispered. The robed man tilted his head slightly. He appeared to think. “Cyrus.” The exhausted man lifted his gaze. “I'll give you a chance to change all of this.”",
      "Cyrus nearly laughed. *He still dares to say that.* “Prove me wrong,” the man continued. “Change the inevitable.” *What nonsense is this. Just kill me.*",
      "A snap. And then everything turned white. An enormous force seized Cyrus from every direction at once, as though reality itself had decided to drag him somewhere else. The battlefield, the fire, the robed man — all of it fell away.",
      "“Will you witness the world's demise once more — O Spectator?”",
      "* * *",
      "Cyrus opened his eyes and gasped. He stared at a familiar ceiling. A soft blue blanket lay across his body. The mattress was beneath him, solid and real. His breathing came in uneven pulls. Wooden walls. The cabinet in the corner. The small window beside the bed. His room.",
      "*What happened. What is happening.* He checked his arms. His hands. Pressed his palm to his chest. No wounds. No scars. Nothing.",
      "*Wait. I can see.*",
      "Knock. Knock. “Cyruuuss!” He froze. He knew that voice. He had not heard it for a very long time. He had believed, for longer than he wanted to remember, that he would never hear it again.",
      "He threw the blanket aside and crossed the room in three strides. He opened the door. The moment he saw her, his vision blurred. She wore a simple brown shirt beneath a yellow-and-white striped apron. Her black hair fell just below her shoulders. Her eyes were a pale greenish color.",
      "*It's really you. I can see you again. I thought I had lost you forever.*",
      "Cyrus stepped forward and wrapped his arms around her. She startled slightly, then returned the embrace. “A very bad dream,” he said. His voice broke somewhere in the middle of it. He pressed his face against her shoulder, and after a moment he stopped trying to hold himself together.",
      "“Well, you're awake now,” she said. “And your beautiful wife is right here beside you.” “I missed you, Cass.” “We literally slept together last night,” Cassandra replied, a small laugh in her voice. *Maybe for you. But not for me.*",
      "As they passed the wall, Cyrus glanced at the calendar. March, 1723. His steps slowed almost imperceptibly. *Three years ago. I have actually returned.* And if he remembered correctly — he felt his face grow warm. Today was the day Cassandra would tell him something that would change his life.",
      "She was pregnant.",
    ],
    notes: [
      { paragraph: 0, label: "Opening image", body: "The battlefield had to arrive before the character. If you meet Cyrus first, the world is exposition; if you meet the fire first, the world is grief.", kind: "creative" },
      { paragraph: 4, label: "The silver grin", body: "Originally a full mask. Reduced to just the painted grin so the reader keeps searching the eyes for tell.", kind: "edit" },
      { paragraph: 17, label: "Crystalline spikes", body: "Kept deliberately abstract — the magic system is revealed by consequence, not by rulebook. Chapter 9 clarifies.", kind: "technical" },
      { paragraph: 24, label: "‘O Spectator’", body: "Title drop. The novel's promise: to watch, again, knowing.", kind: "creative" },
    ],
  },
  {
    id: "ch-02", number: 2, title: "The Weight of What He Knows", minutes: 7, status: "Editing",
    paragraphs: [
      "*She was pregnant.*",
      "The thought circled him as he walked beside her toward the living room, neither fading nor resolving. *Should I pretend I don't know? Should I act surprised? Was it even supposed to happen today?*",
      "The living room was modest. A slightly worn cushion sat beside a low wooden table. The kitchen behind it was simple: stacked plates, utensils gathered in a cup, a fire stove with a pan sitting above it. Two servings already waited on the table — rice, soup, meat.",
      "The smell of the food hit him before anything else. *It has been a long time since I smelled something like this.*",
      "They sat across from each other and ate without rushing. Their home was small — by any objective measure, not much. But Cyrus had always thought that a strange thing to measure.",
      "When they finished, Cassandra set down her towel and looked at him. “Do you have work today?” *Work. What was my — right. Yes.* “I do,” he said. “Sorry, I was distracted.”",
      "He rose and moved to the clothes hanging near the window. He chose a white polo and black trousers. *Is this real? Am I actually here? Even if this is a dream — I don't want to wake up.*",
      "Warmth wrapped around his back without warning. Soft arms enclosed him from behind, a cheek pressing gently against his spine. Cassandra had her arms around him and was looking up with a quiet smile. “Do well at work today,” she said pleasantly. “I shall,” he replied.",
      "Without warning, she tightened her hold. The air left his lungs. His ribs protested. Then a low voice arrived directly beside his ear, stripped of its pleasantness: “DON'T. OGLE. OTHER. WOMEN.”",
      "Despite being unable to breathe, Cyrus felt something loosen in his chest. *Definitely not a dream. Dreams don't cause physical pain.* Which meant one thing: he had truly returned. Unfortunately, that also meant Cassandra's jealousy had returned with him, unchanged and operating at full capacity.",
      "*Cass. You're carrying my child. I'd have to be a complete scoundrel to look at another woman.* He turned around carefully. “Our eleventh monthsary is next week,” he said. “I wouldn't ruin the future we planned together for some stranger.”",
      "The severity in her expression softened. A short exhale escaped her. Almost without realizing it, her hand drifted to rest against her stomach. The moment Cyrus saw it, he understood.",
      "He leaned slightly closer and spoke near her ear. “Besides — we'll have to take care of the little one you're carrying, soon.” He kissed her cheek. Then, before she could process a single word, he was at the door with a bright wave. “See you later!” The door shut behind him.",
      "* * *",
      "Silence filled the house. Cassandra stood completely still. Color rose slowly into her face. She covered her mouth. *How did he know? I discovered it yesterday. I tried to hide it. I was going to surprise him tonight.* She grabbed both sides of her hair and groaned. “I'm such an idiot!”",
      "After a while, the frustration gave way to something smaller and warmer. She sighed, released her hair, and found that despite everything, she was smiling. “I really did marry a man who reads me too well.”",
      "The truth, of course, was simpler than that. It wasn't that Cyrus understood her perfectly. He simply already knew.",
      "* * *",
      "Under the bright morning sun, Cyrus walked through the streets with an unusual lightness in his step. Ahead, a crowd had gathered near a bar. Two men emerged through the saloon doors. One had his hands bound behind his back; the other held him firmly by the arm.",
      "Beside him stood someone in a white polo, black necktie, and dark tuxedo, black gloves covering both hands. Embroidered on the back of each glove was the symbol of a blue crescent moon. The emblem tugged at something in Cyrus's memory. *Where have I seen that?*",
      "He pressed two fingers against his temple and pushed at the memory. Fragments rose and scattered. Nothing resolved. He had forgotten the future. Not all of it — he still knew he was from it, still remembered the broad shape of what had happened. But the details, the specific knowledge that should have guided him through the next three years — it had begun to dissolve, like ink left too long in rain.",
      "Standing in the street, in the ordinary morning light, watching a crowd disperse around two strangers, Cyrus felt afraid for the first time since he had opened his eyes in his own bed.",
    ],
    notes: [
      { paragraph: 8, label: "The all-caps line", body: "Only place in the chapter I let punctuation get loud. Cass gets one moment of theater; the rest of her love is quiet.", kind: "creative" },
      { paragraph: 20, label: "Ink in rain", body: "This is the whole novel's central fear compressed to one image. If the reader doesn't feel it here, the stakes never land.", kind: "technical" },
    ],
  },
  {
    id: "ch-03", number: 3, title: "Diary of the Demised", minutes: 10, status: "Editing",
    paragraphs: [
      "*I forgot.* Two words that burrowed into him and refused to move.",
      "He turned the problem over as he walked. Not amnesia — this wasn't pathological, and whatever was happening to him wasn't ordinary forgetting. He still knew he was from the future. That knowledge remained intact. But the details had begun to dissolve, quietly and without warning, as though his mind were shedding what it could no longer carry.",
      "*Three years forward is three years back. Neither leaves many marks on the body.* But the question persisted. If his memories were already fading, why had he remembered about Cassandra's pregnancy? Was it simply that the most important things went last? *Maybe this is simply the paradox of time. The mind cannot hold two futures at once.*",
      "He was still working through it when he reached his workplace — a three-story building with flat-painted black walls and quadrilateral windows sealed against the morning chill. He climbed the steps, turned the circular doorknob, and stepped inside.",
      "The room was filled with the rhythmic percussion of typewriters. Rows of figures sat bent over their machines, white paper threaded into the platens, fingers moving with the focused urgency of people whose thoughts had deadlines.",
      "A hand landed on his shoulder. “Yo, Cyrus.” Brian, mid-twenties, sharp jawline, holding a white cup from which curled the faint aroma of brewed tea. “Want some?” Cyrus reached for it. Brian immediately withdrew his hand and turned away with a faint smirk. “I'll go make one.” *I thought you were handing it to me.*",
      "Several minutes later, a voice cut across the floor. “Cyrus!” Mary — dark blue hair transitioning to silver at the tips, gathered into a ponytail. “Boss is looking for you.” “I see. Thanks.” He touched her shoulder briefly and withdrew his hand almost as quickly, uncertain what had prompted it. “Imma go smoke,” she added, already turning away. *An elegant woman really shouldn't pick up that habit.*",
      "At the top of the stairs, before a closed silver door, he knocked three times. A prompt male voice from inside: “Come in.” He reached for the knob and pushed. The door didn't move. He tried again. He tried once more. He pulled it instead. It swung open with a slow creak.",
      "*Pull, not push. Noted. I really have forgotten almost everything.*",
      "Behind the rectangular desk sat a man in his thirties, leaning back in his chair. The nameplate on his desk read: Howard Deiter. Howard rose and moved to the bookshelf. He retrieved something from among the documents and brought it to Cyrus.",
      "A brown notebook. Its cover was worn, edged with age, slightly torn at the corners. In curving penmanship on the front were two words: *Bruce Hill*. “A diary?” Cyrus said, before he could stop himself. Howard withdrew a small stack of papers and brought those too. Each sheet held a black-and-white photograph with a brief description below it.",
      "[Prince Blake: 23 Years old. Works as a mail deliverer at DMAA. Single.] [Anderson Silver: 21 Years old. Masseuse. Single.] Then a name caught him. [May Hill: 22 Years old. Works at a dessert restaurant. Married.] He looked up at Howard. “That's Bruce's wife.”",
      "He set the papers aside and opened the diary to its first page. The writing began ordinarily — a photography trip to a yellow-leaf forest, two friends along for company, a wife who couldn't join.",
      "He turned to the next page. [January 12th: We arrived at the yellow leaf forest by noon. After dark, we encountered four teenage boys. No shirts, their lower halves wrapped in yellow fabric. Their skin was thin and pale. They looked lost and starving. We invited them to share our meal. They sat with us without a word — shaking, drooling — and yet they refused to eat.] The right margin continued: [Finally — shelter. My friends and I were relieved not to sleep in the open. The teenagers smiled at us wordlessly and led us inside a cave.]",
      "*I have a bad feeling about this.*",
      "He turned to the next entry. The handwriting had changed. Looser, faster, as if the pen could barely keep pace with the mind behind it.",
      "[In my sleep I smelled burning and woke thinking it was daylight. What I saw instead has not left me since. Anderson had been impaled from below and was rotating in the grasp of flames, his legs already severed, being devoured by two men laughing like demons. Prince was hanging upside down from a cross, his head butchered, his face pinned to the wood with sharpened stakes to keep it from falling. Cannibals. Monsters wearing human skin. I ran while they were still distracted. I reached the carriage and rode with sweat and tears on my face.]",
      "Cyrus's skin prickled. His stomach turned. He did not close the book.",
      "[JANUARY 13TH: I arrived home. Alone. Alone... My wife is here, but I am alone.] [January 14th: I told my wife what happened. She tried many things. None worked.] [January 15th: Those faces. I cannot escape them. I cannot escape. The one who should have died is me.] The page had been torn.",
      "Cyrus turned to what remained and froze. [I should die.] That was all. The words sat at the top of an otherwise empty page. Beneath them — faint, the color of something that had soaked through and dried — was a blush of redness in the paper.",
      "He closed the notebook and set it beside him. He looked at Howard. “Is Bruce —” Howard spoke before he could finish. “He's dead.”",
    ],
    notes: [
      { paragraph: 0, label: "Two-word opening", body: "The whole novel's central fear compressed to two words.", kind: "creative" },
      { paragraph: 16, label: "Bracketed diary voice", body: "Brackets, not italics — Bruce is quoting himself through a diary; Cyrus's inner voice stays italic. Two textures, one page.", kind: "technical" },
    ],
  },
  {
    id: "ch-04", number: 4, title: "Diamond's Charm", minutes: 8, status: "Editing",
    paragraphs: [
      "The words settled into the office like smoke. Cyrus had expected it. The diary had been moving toward that conclusion with its own grim momentum. And yet hearing it stated plainly left a hollow ache in him that expectation had done nothing to prevent.",
      "He thought of the diary's handwriting, loosening entry by entry. Of the guilt Bruce must have carried home from that forest — the unspeakable weight of being the only one who made it out. Of walking into a house shared with a wife who loved him and finding that not even that was enough to reach him anymore. He had left her alone in the end.",
      "Cyrus felt empathy for the man, and then — quietly, almost against his will — a low anger beneath it. That Bruce had chosen to go rather than stay.",
      "“How did he die?” “Shot himself under the chin with a revolver,” Howard said. *A revolver. Did he buy it specifically for this? That isn't impulse. That's a decision made in advance, and followed through.*",
      "Cyrus exhaled slowly. Then a different thought surfaced, unbidden. “Why are you telling me this, Boss?” Howard took a measured breath. “I want you to investigate it.”",
      "*The forest in the diary. Where the four cannibals stood at the tree line with blood on their mouths and pieces of his friends still in their hands.* Cyrus wanted to refuse. He wanted to explain, reasonably, that a journalist had no business walking into something like this. That he had a pregnant wife at home and memories that were dissolving by the hour and no map for what came next.",
      "He was already forming his refusal when Howard spoke again. “Five Diamonds.”",
      "The words landed in Cyrus's mind and everything else stopped. *Diamond. Five of them.* Five Diamonds was equivalent to one hundred and twenty-five thousand copper. More than ten times his monthly wage. Enough for Cassandra's delivery. Enough for food, for the house repairs he had been putting off, for toys he hadn't let himself think about yet. Enough to stop calculating.",
      "Cyrus stood from the cushion. “It shall be done, Sir.” *A man easily moved by money. Cyrus happened to be one of them. Danger? Nothing compared to five diamonds.* The grin lasted about two seconds before he caught it and cleared his throat.",
      "“Will I be going now? Alone?” That last question came out with a faint tremble he didn't bother hiding. “Not right away. Tell your wife first — you have two days before departure. In the meantime, you might begin with Bruce's wife.” He paused. “And no, you won't be going alone. I've hired a bodyguard to accompany you.”",
      "“Where is this person, sir?” “He's quite a shy man. But he's already listening to our conversation. Somewhere in this room.” He added, without blinking: “You can't see him if he doesn't want you to.” *That is genuinely frightening. And somehow I believe it completely.*",
      "Howard smiled with apparent warmth. “If the one guarding you is dangerous, then what waits in that forest is comparatively less so.” Cyrus glanced toward the door. “No, he's not outside the office,” Howard said. *Is he reading my mind, or am I simply that obvious?*",
      "He stood in the hallway with his back against the door and exhaled slowly. *How exactly do I explain to my wife that I'm about to walk into a forest full of cannibals?* Then the answer came to him, simple as gravity. *Five Diamonds.*",
      "On his way home, he passed a market lit by small fires, bought a few ingredients and some meat, and continued on. He arrived at a cement-walled house with a vintage-colored roof and a wooden door. He raised his fist to knock — then caught himself and lowered it. *Right. I ruined the pregnancy surprise. She's had all day to sit with that. Women are formidable when exposed. I'd genuinely rather face the cannibals.*",
      "The door opened before he could knock. Cassandra stood in the frame, wearing a vintage wrap dress that fell to her knees. Her expression was unreadable — and then the moment her eyes found him, it rearranged into a warm smile. “Welcome home.” *Not angry. Good. Wonderful.*",
      "They ate in comfortable quiet at the small table. When the last bites were gone, Cassandra reached across and caught his wrist. “Wait. I have something to ask you first.” A faint rose color had reached her cheeks. She asked: “How did you know I was pregnant?”",
      "He drew a slow breath and answered with the most honest thing he could offer. “We did the deed, didn't we?” Cassandra went red. Not pink — red. She released his wrist with an awkward grace, sat up straight, and began playing with her hair in a way she clearly did not notice herself doing.",
      "“By the way, Cass,” he said, shifting tone. “I received a commission today. A trip to a forest.” Cassandra's brows drew together. “When? And how long?” “I leave in two days. A day's travel by carriage each way — so three days at most.”",
      "“Are you going alone?” “Someone's coming with me. A bodyguard, hired by the boss.” “Who is it?” “I don't know. My boss arranged it.” “A woman?” *You're still worried about that?* “It's a man,” Cyrus said. The tension left her almost at once.",
      "“How much are you paid for this?” He let the silence breathe for just a moment. “Five Diamonds.” Cassandra went very still. Then she raised her right hand toward him, open-palmed and composed. “You can go.”",
    ],
    notes: [
      { paragraph: 6, label: "Five Diamonds", body: "The bribe has to feel unreasonable — it's the only reason Cyrus's ‘better judgment’ loses this scene.", kind: "creative" },
      { paragraph: 10, label: "Invisible bodyguard", body: "Planted, not paid off yet. The reader should file this away and wait.", kind: "technical" },
    ],
  },
  {
    id: "ch-05", number: 5, title: "Investigation", minutes: 9, status: "Editing",
    paragraphs: [
      "The next morning arrived with Cyrus already awake before the sun. He slipped out of the bedroom without disturbing Cassandra. *About four in the morning, if I had to guess.* His shift didn't begin until eight. He had time.",
      "He lit the fire and set a pot on the stove — potato and carrot soup, simple and quick. When he set the empty bowl down, the first thin gold of sunlight was pressing through the window. He washed the bowl and spoon, then retrieved a sheet of blank paper and spent several minutes writing a note for Cassandra.",
      "He dressed — white polo, blazer, brown trousers — then turned to the window to check his reflection. Short black hair. Brown eyes. An ordinary face and an ordinary build. *My wife fell for this face?* He'd never quite solved that mystery.",
      "As his hand neared the knob — a flash. The door was burning. The walls were burning. The entire room was drowning in flame, and inside it a searing pain erupted through his skull. He felt a presence behind him. He turned.",
      "Cassandra stood in the burning room. Her forehead was split open, blood tracing the line of her face down to her lips. The blue dress she wore — stretched across her abdomen — was soaked through in crimson from below the waist. Her eyes were open, and vast, and utterly empty.",
      "Her mouth moved. “None will be saved. None!!!” The voice shook the walls. Cyrus pressed both hands over his ears and held his teeth together.",
      "Then everything was still. He stood at the front door, hand near the knob, heart hammering. The house was ordinary around him. *Was that a vision of something to come?*",
      "Three possible explanations. A warning — a real future event. A symbolic revelation, something inevitable shown in the language of nightmare. Or he was hallucinating, for reasons he couldn't yet identify. He murmured quietly: “I shouldn't think too much of this.”",
      "He opened the door. Something fell from it and landed softly on his shoe. A sealed mail letter. He crouched to pick it up.",
      "[Apologies for the inconvenience, Cyrus, but I neglected to pass on a relevant detail regarding the diary. Bruce's wife, May, works at a coffee-and-tea restaurant located approximately one kilometer southwest of your house. She has brown long hair usually worn in a ponytail, green eyes, and fair white skin. I'll honor the offer of five Diamonds. Thank you. Sincerely, Howard Deiter.]",
      "A few minutes of easy walking brought him to a small restaurant. Above the brown door hung a wood-carved emblem of a coffee cup. *This must be it.* He pushed the door open and stepped inside.",
      "At this hour there were no customers — only a few workers in brown aprons moving through their routines. Behind the long rectangular counter stood a woman. Brown hair in a ponytail. Green eyes. Her face was pale — too pale, the kind that comes from too many skipped meals — and she was staring at nothing, somewhere past the counter, past the room entirely.",
      "She offered him a faint smile and uncapped a pen over a small order pad. “Good morning, sir. May I take your order?” *I didn't come here to drink. But since I'm here.* “Black coffee, two cubes of sugar, please.”",
      "“And also —” She looked up. Cyrus took a breath and bowed slightly. “May I have a moment of your time to speak about your husband, Mrs. May Hill?” The smile left her face. “Manager. I'm taking my break.”",
      "She looked back at Cyrus. “Table three on the right, beside the wall. I'll join you shortly.” He sat against the wall and waited. May arrived at the opposite chair a moment later. Cyrus had already prepared to open the conversation — a journalist's instinct, always the one to initiate. May spoke first.",
      "“Finally. I've been waiting months.” There was relief in her voice, faint but real. Cyrus offered a small bow from his seat. “My condolences for your husband's passing, Mrs. Hill.” She blinked. “Huh?” He straightened, equally confused. Then she said the last thing he expected.",
      "“My husband isn't dead.” “…Huh?”",
    ],
    notes: [
      { paragraph: 4, label: "The vision", body: "Kept intentionally ambiguous. Prophecy or hallucination? The reader has to hold both possibilities for another chapter.", kind: "creative" },
    ],
  },
  {
    id: "ch-06", number: 6, title: "Divulge", minutes: 8, status: "Editing",
    paragraphs: [
      "Cyrus stared at her across the small table. *Then what exactly am I here investigating? Why did my boss hand me this case? Was the diary fabricated? And the last page — the blood, the words —*",
      "May spoke again before he could work through it — quietly, her voice dropping so that it reached only him. “I want you to look for him.” A journalist, being asked to find a missing person. That was a different profession entirely, and a considerably more dangerous one.",
      "“Why not commission an investigator?” “I did. Two months ago. Waited another month for a response and heard nothing — not a single one accepted the work.” *Not because of money, presumably — she seems to be managing. Could all the investigators have been occupied for an entire month? That feels too convenient to be coincidence.*",
      "“How long ago did you submit the diary to us?” “Last week.” *And my boss assigned it to me only yesterday. What was he doing with it in between?*",
      "He picked up his coffee, stirred it once, blew gently on the surface, and took a sip. He set the cup down and folded his arms. “Forgive the delay on our end.” “No, please — I'm just grateful you're here,” May said.",
      "“It's been two months since my husband went missing. All he left behind was that diary.” Her voice began to tremble. She held her own arms as if trying to keep herself still. “A few days after he came home from that forest, he vanished. I found blood on the last page of the diary and heard a loud sound that night. But there was no body. Not anywhere. I will not accept that he's dead without seeing proof of it.”",
      "*Blood on the last page. A loud sound. No body found. The diary ends with 'I should die.' A blood stain. Then nothing. But if Bruce truly died — whether by his own hand or otherwise — why is there no body? And if he didn't die, why would he vanish and leave his wife behind? My boss told me Bruce shot himself. Was that an assumption, or something he claims to know directly?*",
      "“Sir.” He looked up. May was watching him with quiet concern. “Are you alright?” *Asking after a stranger when you're the one suffering. That's a particular kind of person.* “I'm fine. Go on. I'm listening.”",
      "“Since I'm the one asking for this, and I'm aware of the danger involved, I want to compensate you for the risk.” “How much?” “Two Diamonds.” Inside his chest, Cyrus smiled. Outside, he raised an eyebrow. “I appreciate that — but how would I know you have that kind of money?”",
      "“It was my husband's. He left some money in the diary before he went missing. A diamond and twelve gold. The other thirteen gold is mine.” “Your husband had a diamond?” “His work paid well.” “What was his work? The company's name?” May's gaze fell. “I don't know. We've been married two years, and he never told me. Not the name. Not the nature of the work. Nothing.”",
      "*His own wife. Two years. Not even the name of a company.* Cyrus knitted his brows. *The diary mentions photography, but never an employer. He was traveling on what looked like a personal assignment. Either the photography is the cover, or the job he was hiding is something else entirely.*",
      "“Did you ever try to guess why he hid it?” “At first I thought he might be having an affair at work. But two years of coming straight home every evening made that hard to believe. After a while I started thinking the work itself might be dangerous — that the camera was something he used as a cover, that he was earning more than I knew and concealing it.” *The concealment is real. The money is real. The missing body is real.*",
      "“Why are you willing to pay that much?” She didn't pause. “He's my husband.” Three words. No elaboration. No performance. *That's enough.* Cyrus exhaled quietly. The doubt had dissolved. “It's a deal, then, Mrs. Hill.”",
    ],
    notes: [
      { paragraph: 12, label: "Three words", body: "The whole chapter's emotional center. If ‘He's my husband.’ doesn't land, the case is just plot.", kind: "creative" },
    ],
  },
  {
    id: "ch-07", number: 7, title: "Bar", minutes: 8, status: "Editing",
    paragraphs: [
      "May was on her feet before he'd finished the sentence. She reached across the table and took his hands in both of hers, bowing abruptly and deeply. “Thank you. Thank you so much.”",
      "“Keep in mind,” Cyrus said carefully, “I can't promise I'll find him. I can promise I'll try.” May's smile didn't disappear — it changed, settling into something quieter and more resolved than happiness. “Don't worry. And if you fail to find him, I'll still pay you the diamonds.” Cyrus went still. *Ma'am. With that policy, you will be robbed by someone less conscientious than me within the week.*",
      "He stood and reached into his pocket for silver coins. May moved to stop him, her hand closing gently over his. “It's on me. Don't worry about it.” Which was precisely why he pressed the coins into her palm anyway. “Being kind is good. Just be careful who you're kind to.”",
      "Cyrus turned and walked toward the door. He had nearly reached it when it opened from the outside on its own. In the doorway stood a woman in a red dress falling to her knees, embroidered with silver curves, yellow heels, snow-white skin, and familiar eyes. Black hair, hanging loose. “Cass? What are you doing here?” “Cyrus? What are you doing here?”",
      "“I thought you were at work today.” “I was doing work here. You?” “Work? I know what your office looks like. Besides, I only came for a dessert.” “Dessert? Cass, this is a coffee restaurant.” *And you're pregnant. No caffeine.*",
      "Cassandra sighed and pointed her index finger upward. He stepped outside to look. The emblem above the door showed a coffee cup — but studying it more carefully, the cup was decorated in a way that suggested something else entirely. A cake. He returned inside in silence. *No husband wins an argument with his wife.* “I'm sorry,” he said. “Now will you tell me why you're really here?”",
      "Before he could open his mouth, a voice came from behind him. “Your wife?” Both of them turned. May stood behind the counter, watching with genuine curiosity. Cassandra's expression sharpened. “Tell me straight. Who is this woman?”",
      "May bowed slightly. “Pleased to meet you. I'm May Hill. Your husband came to interview me about a case — it concerns my own husband.” *My wife is definitely not pleased. Even with that explanation.* But then Cassandra's expression did something unexpected. It softened. Her hand drifted down to rest against her abdomen — a gesture she probably didn't notice herself making.",
      "May's face lit up immediately. “Oh my.” Before Cassandra could respond, May rounded the counter, took her by the wrist with the cheerful authority of someone who had already decided things, and guided her to the nearest table. *Oh no.*",
      "They sat across from each other. Cassandra lowered herself carefully, one hand on her stomach. May leaned forward on her elbows with bright eyes. “You're pregnant, aren't you?” “Yes.” “Congratulations!!” Cyrus stood to the side of the table and watched them. *They met five minutes ago and they're behaving like old friends.*",
      "“I'll excuse myself,” he said. “Enjoy your conversation, ladies.” Cassandra reached out instinctively as he turned. He was already moving. At the door, he glanced back. Cassandra was watching him. He held her gaze for a moment, gave her a quiet wink, and stepped outside into the morning sun.",
      "He stopped when the bar came into view. *I should look in for a moment.* After a morning like this, a beer was a reasonable ambition.",
      "The bar was dim and comfortable in the way that rooms meant for sitting and forgetting always are. Cyrus settled into a chair beside a man on the left without interrupting. “One samsour beer, please.” “Right on.”",
      "A moment later, the man beside Cyrus laughed — a short, sudden sound. “That kid had some nerve, didn't he?” “What kid?” “The one who stole from this bar. He's become a bit of a local story.” “Oh, him. Impressive he lasted two months before getting caught.” Cyrus's hand stilled on the cup. *Two months.*",
      "“What amazed me most is what he actually stole.” “I never heard.” The bartender set Cyrus's drink down without ceremony. “A revolver,” he said flatly.",
      "The cold moved through Cyrus from the base of his neck to the tips of his fingers. “Did you recover it?” the man asked. “We did. One bullet was missing from the cylinder.” Cyrus pressed his hand over his mouth.",
      "*Two months ago, a revolver was stolen from this bar. One bullet missing. The kid was caught yesterday — the gun recovered. My boss told me Bruce shot himself with a revolver. May said there was no body. If Bruce borrowed the stolen gun to stage his death, and the kid came back to retrieve it — the missing bullet could be the one that was never really fired at anyone.*",
      "*This is far too coincidental.*",
    ],
    notes: [
      { paragraph: 16, label: "The revolver", body: "This is the pivot of the whole first act. Cyrus stops investigating a suicide and starts investigating a stage set.", kind: "technical" },
    ],
  },
  {
    id: "ch-08", number: 8, title: "Dots Connected", minutes: 8, status: "Editing",
    paragraphs: [
      "Cyrus paid for his drink and walked out of the bar. The beer had done nothing. He was colder and more alert than before he'd entered, the morning light sharper than it had any right to be. He headed straight to the office.",
      "When he reached Howard's door, he knocked twice and stepped inside without waiting for a response. Howard was at his desk, leaning back in his chair, one hand propping his cheek with the relaxed patience of a man who had been expecting a visitor. Cyrus shut the door behind him and didn't sit.",
      "He laid out everything. The bar. The stolen revolver. One bullet missing from the cylinder. The timing — two months ago, exactly when Bruce vanished. The kid's capture the previous day. The gun recovered.",
      "Howard listened without moving. When Cyrus finished, he let a few seconds sit between them before speaking, almost to himself. “Bruce is presumed not dead according to his wife. A stolen revolver, one bullet missing, recovered just yesterday. And May said there was no body found.” He paused. “...This doesn't make sense. What I saw was definitely Bruce's suicide.”",
      "The word landed like something dropped from a height. “Saw?” Cyrus asked. His voice was quieter than he intended.",
      "Howard looked at him directly. The stillness in his expression wasn't calm — it was something deliberately constructed over whatever lay beneath. “It's nothing. Continue your investigation. You're dismissed.”",
      "Cyrus didn't move. “Boss. What did you mean — you saw?” The stillness cracked. Howard's eyes narrowed, and the authority his position carried came forward like something that had been waiting quietly at the back of the room all along. “I said you're dismissed.”",
      "Cyrus turned and left. In the hallway, he stood with his back against the closed door. His heartbeat was audible to him. *My boss saw Bruce commit suicide.* That sentence didn't work. There was no plausible reason Howard Deiter would have been present for something like that. No professional reason. No obvious personal one.",
      "*Unless he was there because he arranged it. Or because he was watching for a reason entirely his own.*",
      "*A missing person who might not be dead. A wife who refuses to accept the death without a body. A revolver stolen from a bar, one bullet gone, recovered after the thief was caught. My boss claiming to have witnessed a suicide that may never have happened. And someone in black gloves with a crescent moon emblem who apprehended that thief.*",
      "He had the beginning of a theory, and he immediately started dismantling it. *Wait. If the gun was borrowed — assuming Bruce is alive — how did the kid get it back? Did they meet? If the kid let himself get caught on purpose — why? What does he gain from being in custody?*",
      "He was still in the middle of it when he heard footsteps on the stairs below. A man was ascending. White polo, black necktie, dark tuxedo and trousers. A slight shadow of sleeplessness under pale blue eyes — so pale they might have been mistaken for white from a distance. And on his hands, black gloves with the emblem of a crescent moon stitched at the back. *The man who had restrained the thief.*",
      "The man walked past him without acknowledgment and moved directly toward Howard's office. *He knows my boss. Of course he does. Howard is well connected. This is probably nothing.*",
      "Cyrus started down the stairs. He made it three steps. Then stopped. *Wait a minute.* He turned and walked back up. He knocked on Howard's door — hard, three times. A voice from inside, cool and unbothered: “I'm busy. We'll speak later.”",
      "*He's in there right now, talking to the man with the crescent gloves, about whatever connects them to this case — and I'm out here.* His hand tightened against his side. Then slowly, he unclenched it.",
      "*Enough. I'm done. This isn't my business. Five Diamonds is not worth whatever this is becoming.*",
      "Outside, the streets were ordinary. Then — a chill. Not from the air. The feeling of being watched. He turned and scanned both directions. Nothing stood out. The feeling didn't go away. *Have I pried far enough into this that someone is keeping track of me now?* He said a small, quiet prayer and walked faster toward home.",
    ],
    notes: [
      { paragraph: 3, label: "‘Saw?’", body: "Howard's slip. This is the first crack in the boss character; everything after this reads it differently.", kind: "creative" },
    ],
  },
  {
    id: "ch-09", number: 9, title: "Knowing Is Worse Than Not", minutes: 7, status: "Editing",
    paragraphs: [
      "Daylight. A populated street. These were the kinds of conditions that should have made a person feel safe. They weren't working.",
      "It was ordinary for someone to walk the same direction as you. It was ordinary for paths to align for a block or two before diverging. Cyrus knew this. He kept reminding himself of it as he moved through the crowd, scanning faces with the studied casualness of someone trying not to look like they were scanning.",
      "The feeling of being watched didn't come from a direction. It came from everywhere at once — a pressure against the back of his neck, a sense of eyes with no body he could locate. Every time he turned, the crowd simply continued being a crowd. He rubbed the goosebumps from his arms and accelerated without letting it become a run.",
      "By the time he stepped through the door of his house and turned the lock, he was breathing harder than the walk warranted. Sweat had reached the back of his collar. “Cyrus?” He spun.",
      "The doorknob seared in his grip — burning — and around him the house was suddenly flame. The walls dissolved into fire, the ceiling collapsed into smoke, and the air went thick and unbreathable. He released the knob. Staggered back.",
      "He recognized this. He'd felt it before, at the front door that morning — Cassandra standing before him in a blood-soaked dress, eyes hollow, voice shaking the walls. *If I turn around, I'll see it again.* He didn't want to turn around.",
      "Then a hand touched his shoulder. Reflex took over. He grabbed the wrist, turned hard — and found himself holding his wife's arm as she looked up at him with wide, startled eyes.",
      "The fire was gone. The house was ordinary. The floor was solid. Just the sight of her — alive, whole, wearing the same red dress she'd had on at the restaurant — pulled the tension out of him like a thread through a needle's eye. He released her wrist.",
      "“W-what's wrong, dear?” She was watching him carefully, holding her concern to a measured level. He stepped forward and wrapped his arms around her without saying anything. After a moment they separated, and she looked up at him with the expression of a woman deciding how much to push. “How was work?”",
      "*I'm thinking of quitting is what I should say. But she'd ask why, and I'd have to explain, and explaining would mean telling her about the cannibals and the crescent-moon man and my boss seeing a suicide that may or may not have happened. I am not doing that.*",
      "“Cass —” “By the way,” she said, at exactly the same moment. He stopped. She smiled — the smile of someone who doesn't know the collision they've just caused. “May said she'd like to be our midwife. For free.” Silence. “...Really.”",
      "*I was about to decline her commission. And she preemptively did us a favor of this size.*",
      "His first instinct arrived before he could stop it: “Does she have experience? Has she delivered before?” Cassandra gave him a look. “Does she have to have been a mother herself?” “She delivered a friend's baby three years ago.” “Whose friend? Where?” “I didn't ask. And don't you dare pry.” *Prying is precisely what's been getting me into trouble all day.*",
      "He said none of this aloud. He looked at his wife, who was watching him with the calm certainty of someone who had already made a decision and was simply giving him time to reach the same one. Fate, he thought, was genuinely unreasonable.",
      "*Now I feel indebted to her. Which means I have no grounds to decline. Which means I'm going to that forest.* He exhaled slowly and quietly accepted the inevitable.",
    ],
    notes: [
      { paragraph: 10, label: "The collision", body: "This is the whole chapter's title in one beat. Cass, without knowing it, closes the only exit Cyrus had left.", kind: "creative" },
    ],
  },
  {
    id: "ch-10", number: 10, title: "The Night", minutes: 8, status: "Editing",
    paragraphs: [
      "In a grand opera house where not a single seat was occupied, where rows of red chairs sat empty in the dark and the stage held no audience's expectation — two figures stood beneath the lights.",
      "One was a woman lying on the stage floor, her light blue dress spread around her. Her face was unclear, as faces in dreams often are — but what could be seen was a thin line of crimson running from her forehead, moving slowly, like a petal stained by something it shouldn't have touched.",
      "The other was a man, standing, both arms extended toward the woman. His hands held something. A revolver. Smoke curled from the muzzle. The man lowered his arm. His face was visible. It was Cyrus.",
      "* * *",
      "He gasped awake. The familiar ceiling. Sweat cooling at his temples. His breath arriving in shallow pulls until he caught it. *A dream. Sure doesn't feel like one.*",
      "He sat up and wiped his face. Hallucinations of fire and a dying wife. The persistent sense of invisible eyes in the street. And now a dream in which he stood over a woman with a smoking gun in his hand. *I should have my mental health examined before any of this gets worse.*",
      "A small tug at his thigh pulled him back. He looked down. Cassandra lay beside him, turned slightly inward, her breathing just visible in the stillness. He reached out and ran his fingers gently through her hair, careful not to wake her. *Nevermind. I'm well enough.*",
      "He lay back down. As he settled against the pillow, something small occurred to him. *I've woken before her two days in a row now.* He turned the observation over once, couldn't make anything of it, and let sleep take him.",
      "* * *",
      "He was shaken awake some hours later by a firm, familiar hand. The room was bright. Cassandra stood over him. “Rise and shine, Mr. Deep-Sleeper. Breakfast is ready.” *I was awake before you. You just didn't see it.*",
      "After breakfast he changed into his work clothes and stood at the front door. The day had come. Whatever truth lived inside that yellow forest, he was going to find it. He reached for the knob. A tug at his sleeve stopped him.",
      "He turned. Cassandra was holding the fabric of his sleeve without looking up, her gaze directed at the floor. When she finally raised her face, something was tight in it — something she had been holding since the moment she woke up. “Be careful,” she said. The words were quiet. Not a command. A request. “I will,” he said.",
      "He opened the door and stepped out. Howard stood at the curb. A carriage waited beside him, a horse in harness, no driver's seat occupied. Cyrus walked up without returning the greeting. “Tell me the truth. What did you mean when you said you saw Bruce commit suicide?”",
      "Howard blinked — genuinely, briefly — then smoothed over it. “I said what?” “Yesterday. In your office. You said you saw it. Explain that.” Passersby glanced over. Howard stepped forward and covered Cyrus's mouth with his palm. “Shh.”",
      "“Honestly? Even if I told you, you wouldn't understand it.” “What does that mean?” “Perhaps you'll understand once you've been to the forest.” “That's not an answer. I want the truth from you.” Howard's expression shifted — not to anger, but to something flatter and harder. “I am paying you, Cyrus. Or have you forgotten that?”",
      "The authority in it closed around the conversation. “Or perhaps you no longer want the offer.” It wasn't a question. Cyrus clenched his jaw and climbed up onto the carriage seat. “Where is the bodyguard?” “Already with you.” He looked inside the carriage. Empty. “There's no one in here.” “Believe me just this once. And if you decide not to go — the offer ends the moment you step down.”",
      "Cyrus sat for a long moment. Then he picked up the reins. As the carriage moved and the distance between them grew, Howard's expression shifted into something quiet and private — a slight curve at the corner of his mouth that no one around him was close enough to see.",
    ],
    notes: [
      { paragraph: 0, label: "The empty opera house", body: "Cyrus's role in the whole novel, in one image: a stage, an audience of no one, and a witness who has already done the thing.", kind: "creative" },
      { paragraph: 16, label: "Howard's smile", body: "This is the reader's confirmation that Cyrus is being handled, not helped. From here on the boss is antagonist by weight, not by declaration.", kind: "technical" },
    ],
  },
  {
    id: "ch-11", number: 11, title: "The Whisperer", minutes: 7, status: "Drafting",
    paragraphs: [
      "The sun was already beginning to sink when Cyrus arrived at the edge of the yellow forest.",
      "The sky burned in orange and deep gold, stretching long shadows across the trees as if the world itself was being pulled thin at the edges. He stepped down from the carriage. The forest was quieter than he had expected — no birds, no wind, only the dry crunch of leaves beneath his boots.",
      "He held his torch tightly as the darkness gathered around him. Hours passed. By the time the night arrived fully, the forest had become a void of shifting shadows. He stopped.",
      "Before him was an opening in the earth — exactly as Bruce's diary had described. The same jagged stone mouth. The same darkness beyond it. “So it wasn't fiction,” he murmured. He stepped inside.",
      "*Chapter continues — this is where the uploaded manuscript ends. The rest is being drafted; your bookmarks and notes are saved locally.*",
    ],
    notes: [
      { paragraph: 3, label: "Cave mouth", body: "The chapter's real threshold. Once he steps in, the novel stops being a mystery and starts being a haunting.", kind: "creative" },
    ],
  },
  ...(() => {
    const stubTitles: Record<number, string> = {
      12: "Ash on the Tongue",
      13: "The Cave Beneath the Cave",
      14: "Reins",
      15: "What May Knew",
      16: "The Silver Grin, Remembered",
      17: "Homecoming",
      18: "A Diamond in the Palm",
      19: "The Second Diary",
      20: "Howard's Room",
      21: "The Crescent",
      22: "A Wound That Doesn't Bleed",
      23: "Before the Return",
    };
    const out: Chapter[] = [];
    for (let n = 12; n <= 23; n++) {
      out.push({
        id: `ch-${String(n).padStart(2, "0")}`,
        number: n,
        title: stubTitles[n],
        minutes: 6,
        status: "Drafting",
        paragraphs: [
          `*Chapter ${n} — “${stubTitles[n]}” — is being written. The manuscript for this chapter hasn't been uploaded yet, so this placeholder holds its place in the sequence.*`,
          "* * *",
          "Andre keeps the working outline in a separate document; when the next pass is ready, its full text will drop in here without disturbing your saved reading position or any margin notes you've added.",
          "In the meantime, you can annotate this placeholder — your notes travel with the chapter, not the text.",
        ],
        notes: [
          {
            paragraph: 0,
            label: "Placeholder",
            body: "Full text pending. Your annotations on this chapter are preserved locally either way — the reader stores them per-chapter under this id.",
            kind: "edit",
          },
        ],
      });
    }
    return out;
  })(),
  {
    id: "ch-24", number: 24, title: "The One Who Waited", minutes: 12, status: "Drafting",
    paragraphs: [
      "*This chapter is actively being written.*",
      "The city had learned to keep its lamps low after the second winter. Cyrus walked beneath them and counted the ones that still worked, the way another man might count coins.",
      "He had been told, once, that the price of returning was that you would never again mistake a stranger for someone you loved. He had understood the sentence at the time. He had not understood the weight of it until tonight.",
      "The door of the small house was open. It was never open at this hour. He stopped at the threshold and did not step inside.",
      "“I've been waiting,” said the voice from within. It was not Cassandra's voice. It was not Howard's, or May's, or Brian's. It was a voice he had heard only once before — in a burning field, three years and a lifetime ago.",
      "*— draft continues. Notes below are live commentary from the writing room; expect them to change day to day.*",
    ],
    notes: [
      { paragraph: 0, label: "Status", body: "As of this draft: opening beat is locked, the reveal in paragraph 4 is still on trial. If you're reading and it feels too early, tell me — that's the exact worry I have.", kind: "edit" },
      { paragraph: 1, label: "Lamps as clock", body: "Trying to establish time-passed without a paragraph of exposition. If the ‘counted lamps like coins’ image works, the whole first act condenses to one sentence.", kind: "creative" },
      { paragraph: 4, label: "The voice", body: "This is the return of Chapter 1's antagonist — but I want the reader to feel it in the vowels before they name him.", kind: "technical" },
    ],
  },
];

export const draftingChapter = chapters[chapters.length - 1];
export const chaptersById = Object.fromEntries(chapters.map((c) => [c.id, c]));
